/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.upray.project.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Project service. Represents a row in the &quot;Project_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.upray.project.model.impl.ProjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.upray.project.model.impl.ProjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Project
 * @generated
 */
@ProviderType
public interface ProjectModel
	extends BaseModel<Project>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project.
	 *
	 * @return the uuid of this project
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project.
	 *
	 * @param uuid the uuid of this project
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project.
	 *
	 * @return the user ID of this project
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project.
	 *
	 * @param userId the user ID of this project
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project.
	 *
	 * @return the user uuid of this project
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project.
	 *
	 * @param userUuid the user uuid of this project
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project.
	 *
	 * @return the user name of this project
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project.
	 *
	 * @param userName the user name of this project
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the customer ID of this project.
	 *
	 * @return the customer ID of this project
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this project.
	 *
	 * @param customerId the customer ID of this project
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this project.
	 *
	 * @return the name of this project
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this project.
	 *
	 * @param name the name of this project
	 */
	public void setName(String name);

	/**
	 * Returns the original version of this project.
	 *
	 * @return the original version of this project
	 */
	@AutoEscape
	public String getOriginalVersion();

	/**
	 * Sets the original version of this project.
	 *
	 * @param originalVersion the original version of this project
	 */
	public void setOriginalVersion(String originalVersion);

	/**
	 * Returns the upgrade version of this project.
	 *
	 * @return the upgrade version of this project
	 */
	@AutoEscape
	public String getUpgradeVersion();

	/**
	 * Sets the upgrade version of this project.
	 *
	 * @param upgradeVersion the upgrade version of this project
	 */
	public void setUpgradeVersion(String upgradeVersion);

	/**
	 * Returns the status of this project.
	 *
	 * @return the status of this project
	 */
	public int getStatus();

	/**
	 * Sets the status of this project.
	 *
	 * @param status the status of this project
	 */
	public void setStatus(int status);

	/**
	 * Returns the phase of this project.
	 *
	 * @return the phase of this project
	 */
	public int getPhase();

	/**
	 * Sets the phase of this project.
	 *
	 * @param phase the phase of this project
	 */
	public void setPhase(int phase);

	/**
	 * Returns the deadline of this project.
	 *
	 * @return the deadline of this project
	 */
	public Date getDeadline();

	/**
	 * Sets the deadline of this project.
	 *
	 * @param deadline the deadline of this project
	 */
	public void setDeadline(Date deadline);

	/**
	 * Returns the delivery date of this project.
	 *
	 * @return the delivery date of this project
	 */
	public Date getDeliveryDate();

	/**
	 * Sets the delivery date of this project.
	 *
	 * @param deliveryDate the delivery date of this project
	 */
	public void setDeliveryDate(Date deliveryDate);

	/**
	 * Returns the contract date of this project.
	 *
	 * @return the contract date of this project
	 */
	public Date getContractDate();

	/**
	 * Sets the contract date of this project.
	 *
	 * @param contractDate the contract date of this project
	 */
	public void setContractDate(Date contractDate);

	@Override
	public Project cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}