info:
    description: "Customer REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "CustomerRest"
    version: v1.0
openapi: 3.0.1
components:
    schemas:
        Customer:
            properties:
                customerId:
                    type: string
                name:
                    type: string
            type: object
paths:
    /customer:
        get:
            operationId: getCustomers
            parameters:
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: search
                  required: false
                  schema:
                      type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Customer"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Customer"
                                type: array
                    description: Get all Customers
            tags:
                - Customer
        post:
            operationId: addCustomer
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Customer"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Customer"
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Customer"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Customer"
            tags:
                - Customer
    "/customer/{customerName}":
        delete:
            operationId: deleteCustomer
            parameters:
                - in: path
                  name: customerName
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Customer"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Customer"
            tags:
                - Customer
    "/customer/{customerId}":
        put:
            operationId: updateCustomer
            parameters:
                - in: path
                  name: customerId
                  required: true
                  schema:
                      type: integer
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Customer"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Customer"
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Customer"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Customer"
            tags:
                - Customer