/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.upray.customer.model.impl;

import com.upray.customer.model.Customer;
import com.upray.customer.service.CustomerLocalServiceUtil;

/**
 * The extended model base implementation for the Customer service. Represents a row in the &quot;Customer_Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerImpl}.
 * </p>
 *
 * @author Matheus Granville
 * @see CustomerImpl
 * @see Customer
 * @generated
 */
public abstract class CustomerBaseImpl
	extends CustomerModelImpl implements Customer {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer model instance should use the <code>Customer</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CustomerLocalServiceUtil.addCustomer(this);
		}
		else {
			CustomerLocalServiceUtil.updateCustomer(this);
		}
	}

}